version: '3'

services:
  php:
    build: .
    image: hdvianna/parallel-workpool-dev
    volumes:
      - .:/var/local/parallel-workpool
    command: >
      sh -c "tail -f /dev/null && \
        composer install -vvv"